# Site settings
title: 'Vincent De Schutter'
description: 'Tech junkie • Security enthousiast • Computer Science @ VUBrussels'
url: 'http://vincentds.be'
baseurl: '/'
google_analytics: 'UA-51543309-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Vincent De Schutter'
  email: vdeschut@skynet.be
  twitter_username: vdeschutter
  facebook_username: vincent.deschutter
  github_username:  VincentDS
  linkedin_username:  vincent-de-schutter-74678aa6

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'default'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
