# Site settings
title: 'Vincent De Schutter'
description: 'Tech junkie • Security enthusiast • Computer Science @VUBrussels & @ETHZurich'
hackerone: 'hackerone.com/vincentds'
url: 'http://vincentds.be' 
#url: 'http://localhost:4000'
baseurl: '/'
google_analytics: 'UA-51543309-1'
disqus_shortname: 'vincentdsblog'

author:
  name: 'Vincent De Schutter'
  email: vdeschut@skynet.be
  twitter_username: vdeschutter
  facebook_username: vincent.deschutter
  github_username:  VincentDS
  linkedin_username:  vincent-de-schutter-74678aa6

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
